### ISSUE TITLE
Remove company users

### ISSUE THREAD

**Issue by CyberneticCoding** [CyberneticCoding/schedulelink#32]
As an owner of a company, i want to be able to remove users from the company, so i can keep the security of the data of my employees.

1. Every normal user should be able to be removed.
2. After removing, the user still exists, but no longer is coupled with the company
3. After removing, the user no longer can see the company details.
4. Owners are not able to be removed
6. Only owner is able to remove users from company 

Tests:
feature: test_company_owner_can_remove_users
feature: test_user_cannot_remove_users_from_active_company
e2e: test_company_delete_member

**Comment by TOKEN-NL** [comment]
kijken of tests geschreven zijn en zo niet schrijven :)
